databases:
  - name: daamkemon-db
    databaseName: daamkemon
    user: daamkemon
    plan: free

services:
  - type: redis
    name: daamkemon-redis
    plan: free
    ipAllowList: [] # Only allow internal connections

  - type: web
    name: daamkemon-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: daamkemon-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: daamkemon-redis
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: RUN_ON_STARTUP
        value: "true"
